# Generated by Django 5.2.5 on 2025-09-03 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtask_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='JobAssignment',
        ),
        migrations.AlterModelOptions(
            name='jobassignment',
            options={'ordering': ['-created_at']},
        ),
    ]
