# Generated by Django 5.2.5 on 2025-09-03 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_options_alter_equipment_created_at_and_more'),
        ('jobs', '0006_job_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Assignment', 'verbose_name_plural': 'Job Assignments'},
        ),
        migrations.AlterModelOptions(
            name='jobtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Technician or user assigned to the job.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='client_name',
            field=models.CharField(help_text='Name of the client associated with the job.', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the job.', on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the job.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text='Indicates whether the job is overdue.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the job.', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Scheduled date for the job.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', help_text='Current status of the job.', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Title of the job.', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the task was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the task.'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='equipments',
            field=models.ManyToManyField(blank=True, help_text='Equipment associated with this task.', related_name='task_assignments', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job this task belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', help_text='Current status of the task.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='title',
            field=models.CharField(help_text='Title of the task.', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.'),
        ),
    ]
