# Generated by Django 5.2.5 on 2025-09-02 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=80)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('crated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_crated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['serial_number'], name='equipment_e_serial__b7639f_idx')],
            },
        ),
    ]
