# Generated by Django 5.2.5 on 2025-09-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='crated_by',
            new_name='created_by',
        ),
    ]
