# Generated by Django 5.2.5 on 2025-09-03 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_rename_crated_by_equipment_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this equipment record.', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Name of the equipment (e.g., Air Compressor).', max_length=120),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number of the equipment.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(help_text='Category/type of the equipment (e.g., Electrical, Mechanical).', max_length=80),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.'),
        ),
    ]
